# Generated by Django 4.0.2 on 2022-02-08 19:58

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='indir.png', upload_to=users.models.user_profile_path),
        ),
    ]
