export const data = [
  {
    id: 1,
    img: "https://images-na.ssl-images-amazon.com/images/I/81eB%2B7%2BCkUL._AC_UL200_SR200,200_.jpg",
    title: "I Love You to the Moon and Back",
    author: "Amelia Hepworth",
    price: "1.55",
  },
  {
    id: 2,
    img: "https://images-na.ssl-images-amazon.com/images/I/71aLultW5EL._AC_UL200_SR200,200_.jpg",
    title: "Our Class is a Family",
    author: "Shannon Olsen",
    price: "4.59",
  },
  {
    id: 3,
    img: "https://images-na.ssl-images-amazon.com/images/I/71e5m7xQd0L._AC_UL200_SR200,200_.jpg",
    title: "The Vanishing Half: A Novel",
    author: "Brit Bennett",
    price: "11.29",
  },
  {
    id: 4,
    img: "https://images-na.ssl-images-amazon.com/images/I/81lsmyMcYNL._AC_UL200_SR200,200_.jpg",
    title: "American Marxism",
    author: "Mark R. Levin",
    price: "14.00",
  },
  {
    id: 5,
    img: "https://images-na.ssl-images-amazon.com/images/I/91S+nNHdHSL._AC_UL200_SR200,200_.jpg",
    title:
      "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    author: "James Clear",
    price: "11.98",
  },
  {
    id: 6,
    img: "https://images-na.ssl-images-amazon.com/images/I/91lk9FG9xQL._AC_UL200_SR200,200_.jpg",
    title: "The Four Agreements: A Practical Guide to Personal Freedom",
    author: "Don Miguel Ruiz",
    price: "5.77",
  },
  {
    id: 7,
    img: "https://images-na.ssl-images-amazon.com/images/I/81nzxODnaJL._AC_UL200_SR200,200_.jpg",
    title: "If Animals Kissed Good Night",
    author: "Ann Whitford Paul",
    price: "4.44",
  },
  {
    id: 8,
    img: "https://images-na.ssl-images-amazon.com/images/I/61NdJMwAThS._AC_UL200_SR200,200_.jpg",
    title:
      "The Body Keeps the Score: Brain, Mind, and Body in the Healing of Trauma",
    author: "Bessel van der Kolk M.D.",
    price: "11.40",
  },
  {
    id: 9,
    img: "https://images-na.ssl-images-amazon.com/images/I/71eJk7GtUOL._AC_UL200_SR200,200_.jpg",
    title: "The Boy, the Mole, the Fox and the Horse",
    author: "Charlie Mackesy",
    price: "10.35",
  },
  {
    id: 10,
    img: "https://images-na.ssl-images-amazon.com/images/I/71xUvuJiqgL._AC_UL200_SR200,200_.jpg",
    title: "It Ends with Us: A Novel",
    author: "Colleen Hoover ",
    price: "9.47",
  },
  {
    id: 11,
    img: "https://images-na.ssl-images-amazon.com/images/I/91+CnxqOEQS._AC_UL200_SR200,200_.jpg",
    title: "The Four Winds: A Novel",
    author: "Kristin Hannah",
    price: "14.02",
  },
  {
    id: 12,
    img: "https://images-na.ssl-images-amazon.com/images/I/81RuAzKrHkL._AC_UL200_SR200,200_.jpg",
    title: "The 5 Love Languages: The Secret to Love that Lasts",
    author: "Gary Chapman",
    price: "7.57",
  },
];
